#!/usr/bin/env python3
import re
import sys

ALLOWED_TYPES = frozenset([
    'feat', 'fix', 'docs', 'test', 'refactor', 'chore', 'ci', 'build', 'perf',
])

FORBIDDEN_TERMS = frozenset([
    'claude', 'chatgpt', 'gpt-4', 'gpt4', 'copilot', 'gemini',
    'openai', 'anthropic', 'cursor', 'codeium', 'tabnine',
    'generated by', 'ai-generated',
])

PATTERN = re.compile(r'^(?P<type>[a-z]+)(?:\([^)]+\))?!?: (?P<desc>.+)$')


def read_message(path):
    with open(path) as f:
        lines = [l.rstrip() for l in f if not l.startswith('#')]
    return '\n'.join(lines).strip()


def validate(message):
    errors = []
    subject = message.splitlines()[0] if message else ''

    if not subject:
        return ['commit message is empty']

    m = PATTERN.match(subject)
    if not m:
        errors.append(
            f'does not match conventional format (type(scope): description)\n'
            f'  got: {subject!r}'
        )
    else:
        commit_type = m.group('type')
        if commit_type not in ALLOWED_TYPES:
            errors.append(
                f'unknown type {commit_type!r} — allowed: {", ".join(sorted(ALLOWED_TYPES))}'
            )
        if not m.group('desc').strip():
            errors.append('description is empty after the colon')

    lowered = message.lower()
    for term in FORBIDDEN_TERMS:
        if term in lowered:
            errors.append(f'contains forbidden term: {term!r}')

    return errors


def main():
    if len(sys.argv) < 2:
        print('usage: validate_commit_message.py <commit-msg-file>', file=sys.stderr)
        sys.exit(2)

    message = read_message(sys.argv[1])
    errors = validate(message)

    if errors:
        print('commit message rejected:', file=sys.stderr)
        for e in errors:
            print(f'  - {e}', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
